### ISSUE TITLE
Incorrect value in case of delay

### ISSUE THREAD

**Issue by xMuehlex** [FaserF/ha-deutschebahn#1]
**Describe the bug**
In the case of a late evening delay, where a train arrives after 0:00, the delay is output as a negative value.

**Expected behavior**
The delay should be output as a positive number in minutes
![IMG_5852](https://user-images.githubusercontent.com/89790571/192875194-c611e1ec-f695-4e67-9f2d-8ff0c063ca4e.PNG)

**Version Details**
- Homeassistant Version: 2022.8.6
- DB Integration Version: 1.0.1

**Comment by FaserF** [comment]
Unfortunatly that is a dependency issue, see here:
https://github.com/kennell/schiene/blob/01284d7786f2b2ba2328ddf56900ac73f927f56b/schiene/schiene.py#L103

I will try to fix it in the dependency and ask kennel to merge it into https://github.com/kennell/schiene

**Comment by FaserF** [comment]
Fixed with release 1.0.2

**Comment by FaserF** [comment]
Version 1.0.2 has been released. It should fix the issue. Please let me know if the issue still exists afterwards.
