### ISSUE TITLE
[Feature Request] Allow to add the same connection again, once direct once non-direct

### ISSUE THREAD

**Issue by mnbrgr** [FaserF/ha-deutschebahn#11]
Currently it is not possible to have a sensor for direct and one for non direct for the same connection at the same time. However, this would be interesting e.g. to know if it makes sense to wait a bit longer in favor of having a direct connection.

**Comment by mnbrgr** [comment]
It's actually working. No clue what did I do wrong the first time.

**Comment by FaserF** [comment]
Thanks for the feedback!
