### ISSUE TITLE
[Feature Request]: information on next and next_on trains

### ISSUE THREAD

**Issue by M-See** [FaserF/ha-deutschebahn#16]
### The request

I just wanted to know whether it´s already possible or can easily be implemented that one gets the same information for the next and next next trains as for the real next train.

Same issue as here:

https://community.home-assistant.io/t/extension-of-deutsche-bahn-sensor/349958

Is that possible?

**Comment by Mattis-Seehaus** [comment]
Just too easy!

Fixed it by adding the parameters for the next and next next trains here:

`    @property
    def extra_state_attributes(self):
        """Return the state attributes."""
        if len(self.connections) > 0:
            connections = self.connections[0]
            if len(self.connections) > 1:
                connections["next"] = self.connections[1]["departure"]
                connections["next_delay"] = self.connections[1]["delay"]
                connections["next_canceled"] = self.connections[1]["canceled"]
            if len(self.connections) > 2:
                connections["next_on"] = self.connections[2]["departure"]
                connections["next_on_delay"] = self.connections[2]["delay"]
                connections["next_on_canceled"] = self.connections[2]["canceled"]`
                
                Thank you very much for the general scripts :)!

**Comment by M-See** [comment]
In Version 2.1.0, this doesn´t seem to work anymore, so i downgraded again and added the lines to the original code again, to make it work.

For Version 2.0.4 the following result was obtained by adding the lines above:
![123](https://github.com/FaserF/ha-deutschebahn/assets/60132687/761bd77a-42bd-458d-80c8-e655c3b0a9d2)

In version 2.1.0, the attributes of the last line were completely undefined, but I have not yet found out which commits this refers to.

**Comment by M-See** [comment]
Ah.. solved by setting the max. number of connections to 3 from the UI of the 2.1.0 version.

Thanks for the additonal features :)!
