### ISSUE TITLE
[Feature Request]: Add attributes 'departure_current' and 'arrival_current'

### ISSUE THREAD

**Issue by bcutter** [FaserF/ha-deutschebahn#25]
### The request

Add two new attributes:
- combine the existing `departure` attribute with the also existing `delay` attribute to provide the new `departure_current` attribute
- combine the existing `arrival` attribute with the also existing `delay_arrival` attribute to provide the new `arrival_current` attribute

This way we can easily get the **actual (current)** departure / arrival times. No additional math on user side needed.

### Is your feature request related to a problem?

```txt
The problem is, that if you have "16:47 +23" you have to calculate on your own (either in your head or by additional templating involving some significant Jinja magic) what the actual time including the delay is.
```

### Additional information

https://community.home-assistant.io/t/configuration-deutsche-bahn-integration/402377/10

**Comment by FaserF** [comment]
Please give it a try with the new version 3.0.0-b1
https://github.com/FaserF/ha-deutschebahn/releases/tag/3.0.0-b1

**Comment by bcutter** [comment]
Works great! Installed https://github.com/FaserF/ha-deutschebahn/releases/tag/3.0.0, adjusted my whole GUI (quite a lot of work with all the attributes, especially as the native attribute card can not handle arrays so I had to switch to `custom:template-entity-row` and do everything by hand) and added the new attributes.

Perfect, thank you very much! Those new attributes are very helpful.
