### ISSUE TITLE
[Feature Request]: products to ignore: BUS

### ISSUE THREAD

**Issue by Dino0811** [FaserF/ha-deutschebahn#29]
### The request

Hi,
is it possible to add an ignore option?

products to ignore: BUS

because i wan't to use S-BAHN / STR, but not BUS. But in my case the api also uses "BUS" for next connections

**Comment by roandreas** [comment]
Same for EST for the new connection from Cologne to Aachen. Not possible to ignore it.
Any possible? Is it connected to Schiene?

**Comment by FaserF** [comment]
Please give it a try with the new version 3.0.0-b1
https://github.com/FaserF/ha-deutschebahn/releases/tag/3.0.0-b1
