### ISSUE TITLE
Typo in products to ignore

### ISSUE THREAD

**Issue by jorgwolski** [FaserF/ha-deutschebahn#32]
### The problem

The abbreviation for the Train à Grande Vitesse in product to ignore is stated as TVG. On the DB website it is called TGV.

### What version of Home Assistant Core has the issue?

Core-2024.2.2

### What version of DeutscheBahn Integration has the issue?

2.2.0

### What type of installation are you running?

Home Assistant OS

**Comment by FaserF** [comment]
Is this what you are meaning?
![image](https://github.com/FaserF/ha-deutschebahn/assets/12374134/0e5d2c55-fa3b-4755-adc4-7cddbfe5c1f0)

**Comment by FaserF** [comment]
Thank you for pointing out! Fixed with release 2.2.1
