### ISSUE TITLE
HomeAssistantType is deprecated warning

### ISSUE THREAD

**Issue by Failure404** [FaserF/ha-deutschebahn#35]
### The problem

Hi,
since Home Assistant 2024.5.0 there is the following warning:

HomeAssistantType was used from deutschebahn, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'deutschebahn' custom integration.

Thanks in advance for fixing!

### What version of Home Assistant Core has the issue?

2024.5.0

### What version of DeutscheBahn Integration has the issue?

2.2.1

### What type of installation are you running?

Home Assistant Supervised

**Comment by duczz** [comment]
@FaserF do you will update this?

**Comment by FaserF** [comment]
Fixed with Version 2.2.2, available now
