### ISSUE TITLE
GUI description missing

### ISSUE THREAD

**Issue by bcutter** [FaserF/ha-deutschebahn#43]
### The problem

Two GUI configuration elements are not well/described at all:

![grafik](https://github.com/user-attachments/assets/68ca0c5e-587b-4002-9171-7ce2bbd07921)

I guess
1 = maximum connections
2 = scan interval

Anyway, the GUI description needs a minor revision.

### What version of Home Assistant Core has the issue?

core-2023.9.3

### What version of DeutscheBahn Integration has the issue?

3.0

### What type of installation are you running?

Home Assistant OS

**Comment by FaserF** [comment]
Thanks for letting me know! Fixed with Version 3.0.1
