### ISSUE TITLE
Incorrect unique_id stored in HA config when adding a new train connection

### ISSUE THREAD

**Issue by mareklab** [FaserF/ha-deutschebahn#5]
### The problem

When the user saves a new connection, you currently store the start station as `unique_id` in HA config. 
This is incorrect because this way you cannot retrieve a schedule from the same train station more than once (abort error is shown), regardless of the train destination.

My proposal is to store the combination of both start and destination stations as the unique_id. I've modified HA config manually in that way and it works fine.

### What version of Home Assistant Core has the issue?

core-2022.10.4

### What version of DeutscheBahn Integration has the issue?

2.0.1

### What type of installation are you running?

Home Assistant Container

**Comment by kgroshert** [comment]
I was just about to open a similar issue. If I try to setup 2 connections from the same starting-point I get "This start & Destination combination is already configured", probably because of this issue.

**Comment by FaserF** [comment]
Version 2.0.2 now generates unique IDs. Please try it again with this release and let me know if this fixed the issue.

**Comment by FaserF** [comment]
fixed with version 2.0.3, please give it a try

**Comment by mareklab** [comment]
@FaserF It seems to work fine, thank you! 😍
