### ISSUE TITLE
feature request: current location to station

### ISSUE THREAD

**Issue by beber-msft** [FaserF/ha-deutschebahn#8]
Hello,
can you please enable a sensor leveraging location entities as source? I.e. wherever I am, show me the next train home please.
thank you!

**Comment by FaserF** [comment]
Sounds like a very good idea. But unfortunately I don’t think that this can be done.
The deutsche Bahn api is pretty specific with the inputs about the start location. This can only hardly be generated by coordinates or a city. Even if I would implement it then it most likely would throw many errors / unavailable messages when you are on a road or a small village with no DB traffic.

**Comment by FaserF** [comment]
But this could maybe be archived with the new Hafas integration:
https://github.com/home-assistant/core/pull/78839
